"use strict";

var TrainExplorerConstants = {
  LOAD: "TRAIN_EXPLORER_LOAD",
  LOAD_SUCCESS: "TRAIN_EXPLORER_LOAD_SUCCESS",
  LOAD_FAIL: "TRAIN_EXPLORER_LOAD_FAIL",
  CALLING_POINTS_LOAD: "CALLING_POINTS_LOAD",
  CALLING_POINTS_LOAD_SUCCESS: "CALLING_POINTS_LOAD_SUCCESS",
  CALLING_POINTS_LOAD_FAIL: "CALLING_POINTS_LOAD_FAIL",
  UPDATE_ROUTE: "TRAIN_EXPLORER_UPDATE_ROUTE"
};

module.exports = TrainExplorerConstants;
